### ISSUE TITLE
Failed to create drawable

### ISSUE THREAD

**Issue by rmulr** [Genymobile/genymotion-kernel#3]
Hey there again,

i know its might be off optic here but i am trying for days now getting Geymotion running on my server, which seems to be more complicated than anything else done so far...

E-Mail Support by Genymotion is incredible slow and i do not get any reply here. Maybe somebody can help me with here?

Now after solving problems with missing drivers and so on i get this new error message when trying to start any virtual device.

> "failed to create drawable"

Screen
https://postimg.org/image/vl5fxsyq3/

Whats does this means and any idea how to fix this?

**Comment by fbarthelery** [comment]
I'm sorry to hear that you keep having issues with Genymotion. However, support on the product is only provided via the [support page](https://www.genymotion.com/contact/). It is very important for us, that you use this medium so that we can centralize and keep a track on your issues. Our support team is actively working on this and will do its best to help you achieve your use case and fix the issues that you may have.

This Github project is dedicated to the Linux kernel used by Genymotion virtual devices.
